name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    strategy:
      matrix:
        optimize: [Debug, ReleaseSmall, ReleaseSafe, ReleaseFast]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: master
          cache-key: ${{ matrix.optimize }}
      - run: zig build test -Doptimize=${{ matrix.optimize }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - run: zig fmt --check .
